mj:
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  accounts:
    - guild-id: 1244928681713995776
      channel-id: 1244928681713995780
      user-token: MTIyNDI3MjU5MzcwMDM4ODg4NA.Gfprg8.DhOvergKiOvYhT49MxNt-CMo7Mztf0I30K_nN0
      
