mj:
  accounts:
    - guild-id: "${MJ_ACCOUNT_1_GUILD_ID}"       
      channel-id: "${MJ_ACCOUNT_1_CHANNEL_ID}"   
      user-token: "${MJ_ACCOUNT_1_USER_TOKEN}"   
      user-agent: "${MJ_ACCOUNT_1_USER_AGENT}"   
    - guild-id: "${MJ_ACCOUNT_2_GUILD_ID}"       
      channel-id: "${MJ_ACCOUNT_2_CHANNEL_ID}"   
      user-token: "${MJ_ACCOUNT_2_USER_TOKEN}"   
      user-agent: "${MJ_ACCOUNT_2_USER_AGENT}"  
  task-store:
    type: in_memory  
    timeout: 30d    
  translate-way: null            
