mj:
  task-store:
    type: in_memory  
    timeout: 30d   
  translate-way: null
  accountChooseRule: RoundRobinRule  # 负载均衡策略
  accounts:
    - guild-id: "${mj_discord_guild_id}"
      channel-id: "${mj_discord_channel_id}"
      user-token: "${mj_discord_user_token}"
      enable: true
      core-size: 3
      queue-size: 10
      timeout-minutes: 5
    - guild-id: "${mj_discord_guild_id_2}"
      channel-id: "${mj_discord_channel_id_2}"
      user-token: "${mj_discord_user_token_2}"
      enable: true
      core-size: 3
      queue-size: 10
      timeout-minutes: 5
