mj:
  task-store:
    type: in_memory  
    timeout: 30d   
  translate-way: null
  accountChooseRule: RoundRobinRule  # 负载均衡策略
  accounts:
    - guildId: ${mj_discord_guild_id}
      channelId: ${mj_discord_channel_id}
      userToken: ${mj_discord_user_token}
      enable: true
      coreSize: 3
      queueSize: 10
      timeoutMinutes: 5
    - guildId: ${mj_discord_guild_id_2}
      channelId: ${mj_discord_channel_id_2}
      userToken: ${mj_discord_user_token_2}
      enable: true
      coreSize: 3
      queueSize: 10
      timeoutMinutes: 5
